// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using neshto_si.DataBase;

namespace neshto_si.Migrations
{
    [DbContext(typeof(Madura3))]
    [Migration("20210506190807_madura3vol1")]
    partial class madura3vol1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("neshto_si.DataBase.Models.Line", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("arrival")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("departure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("train_lineid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("train_lineid");

                    b.ToTable("lines");
                });

            modelBuilder.Entity("neshto_si.DataBase.Models.Ticket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("train_ticketid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("train_ticketid");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("neshto_si.DataBase.Models.Train", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("trains");
                });

            modelBuilder.Entity("neshto_si.DataBase.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("role")
                        .HasColumnType("bit");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("neshto_si.DataBase.Models.Line", b =>
                {
                    b.HasOne("neshto_si.DataBase.Models.Train", "train_line")
                        .WithMany()
                        .HasForeignKey("train_lineid");

                    b.Navigation("train_line");
                });

            modelBuilder.Entity("neshto_si.DataBase.Models.Ticket", b =>
                {
                    b.HasOne("neshto_si.DataBase.Models.Train", "train_ticket")
                        .WithMany()
                        .HasForeignKey("train_ticketid");

                    b.Navigation("train_ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
